# Generated by Django 5.0.2 on 2024-06-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpostrelation',
            name='likes',
            field=models.BooleanField(default=False),
        ),
    ]
