# Generated by Django 5.0.2 on 2024-07-01 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_userpostrelation_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpostrelation',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post'),
        ),
    ]
